# Generated by Django 2.0.1 on 2023-10-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_auto_20231001_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.CharField(max_length=100),
        ),
    ]
