# Generated by Django 2.0.1 on 2023-10-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0004_auto_20231001_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
