# Generated by Django 2.0.1 on 2023-10-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0005_auto_20231001_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='request',
            name='author',
            field=models.CharField(max_length=20),
        ),
    ]
