# Generated by Django 2.0.1 on 2023-10-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0006_auto_20231001_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='address',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='request',
            name='reason',
            field=models.TextField(max_length=100),
        ),
    ]
