# Generated by Django 2.0.1 on 2023-10-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0008_auto_20231005_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='telnumber',
            field=models.IntegerField(),
        ),
    ]
