# Generated by Django 2.0.1 on 2023-10-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0010_auto_20231005_1409'),
    ]

    operations = [
    ]
