# Generated by Django 2.0.1 on 2023-10-05 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0011_auto_20231005_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='dateexpired',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='datejoined',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
