# Generated by Django 2.0.1 on 2023-10-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0013_auto_20231005_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='confirmprofession',
            field=models.CharField(default='X', max_length=100),
        ),
    ]
